version: '3.8'

services:
  temperature-api:
    build: ./temperature-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smart_home
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
